// Generated by CoffeeScript 1.3.3
(function() {
  var app, express;

  express = require('express');

  app = module.exports = express.createServer();

  app.configure(function() {
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser());
    app.use(express.session({
      secret: '&8d@dsg562#nv+='
    }));
    app.set('view engine', 'html');
    app.set('views', __dirname + '/public/tmpl');
    app.set('view options', {
      layout: false
    });
    app.use(express["static"](__dirname + '/public'));
    return app.register('.html', {
      compile: function(str, options) {
        return function(locals) {
          return str;
        };
      }
    });
  });

  app.configure('development', function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure('production', function() {
    return app.use(express.errorHandler());
  });

  app.get('/', function(req, res) {
    return res.render('index.html');
  });

  app.listen(8080, function() {
    return console.log("Express server listen on port %d in %s mode", app.address().port, app.settings.env);
  });

}).call(this);
